### ISSUE TITLE
AppVeyor checks fail

### ISSUE THREAD

**Issue by PaulWalkerUK** [lazywinadmin/SpaceX#24]
The automated AppVeyor checks keep failing with:

```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```
(E.g. https://ci.appveyor.com/project/lazywinadmin/spacex/builds/19498326)

I'm not an expert on AppVeyor, but I've seen other repos that have the `appveyor.yml` file in the repository - not sure if there are any drawbacks to doing this.

It would also be good to get AppVeyor to run Pester tests, once they're there (#1)

**Comment by lazywinadmin** [comment]
I'll work on this :) thanks for opening an issue!

**Comment by lazywinadmin** [comment]
Got most of them working.
I'll have to investigate some issues I had with the functions specific tests
